### ISSUE TITLE
Unexpected behaviour in page count

### ISSUE THREAD

**Issue by mjklin** [titoBouzout/WordCount#40] opened 2015-01-22 19:50 UTC
Hi, thanks for adding the "current page" option! Unfortunately, I'm getting some unexpected behaviour now. Usually, the total page count will change depending on where I click in the document (from 19 to 25 to 21, for example). Hopefully this is an easy fix?

Thanks again!

**Comment by titoBouzout** [comment] 2015-01-22 19:55
the page count is taken from the visible lines, the visible lines reduce at
the end of the document, that will make the amount of pages vary, I know is
not the better but well can you add a blank page at the end? or disable
"scroll_past_end_" in ST preferences... In any case, I would appreciate a
test case. Thanks

**Comment by mjklin** [comment] 2015-01-23 02:09
Hmm, I tried both of your suggestions and neither one worked. Still getting changing numbers.

Can you not do a simple script that does (current line number / 300) / (total lines / 300) ?

**Comment by titoBouzout** [comment] 2015-01-23 03:25
o.O

**Comment by titoBouzout** [comment] 2015-01-23 06:07
okei done as you suggested

**Comment by mjklin** [comment] 2015-01-23 16:54
o.O

this is the behaviour I get with "page_count_mode_count_words": false  

http://i.imgur.com/UXLODD2.gif

I guess it's not as easy as I thought? Wish I was smart enough to figure it out...anyway I appreciate your work!

**Comment by titoBouzout** [comment] 2015-01-23 17:13
Please, the number changes when you hit the bottom of the document? That's expected behaviour if you turn off "page_count_mode_count_words", because it takes the number of rows in a page from the visible lines, and that changes, if you hit the final of the document.

If you want to count words as pages, then turn it on. That does not alter page count. 

 Can you please add a testcase, a real one. I mean, something like:
1. Paste this text: balabalabba
2. Click line 4, "it should display" Page 1/4
2. Click line 14, "it should display" Page 2/4 but instead ...

Thank you!

That you may ignore how to do a ST package does not mean you are not smart, just that you don't know, and its ok to not know some things :) hehe

**Comment by titoBouzout** [comment] 2015-01-28 16:38
OKei, in lack of more information I'm closing

**Closed as completed** 2015-01-28 16:38 UTC

**Comment by mjklin** [comment] 2015-02-05 15:37
I think I'm getting most of what I wanted from your addon, so I can't complain :) 

Really all I wanted was to see approximately how far I was through the document, and your addon provides that even if the page count varies. Good enough!
